#
###################################
# Site wide configuration
####################################
#
title: vimysql
email: 702367@qq.com
description: vimysql's blog,powered by jekyll.
url: https://vimysql.github.io # the base hostname & protocol for your site
keywords: ["jekyll", "oracle", "sql","blog"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Nanjing
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-gist
  - jemoji

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: vimysql
  avatar: avatar.jpg
  job: "Oracle DBA"
  bio: "A Oracle DBA who like play computer games. Working for LIANLIFE at in Nanjing, China."
  email: 702367@qq.com
  disqus-shortname: #username
  twitter:  #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: vimysql #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: http://blog.sina.com.cn/jinzhihen
  flickr: #username
  codepen: #username
  telegram: #username
